basePath: /api
definitions:
  httputil.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.AddCategoryInput:
    properties:
      title:
        type: string
      visibility:
        type: integer
    type: object
  model.AddFeedInput:
    properties:
      categoryId:
        type: integer
      feedUrl:
        $ref: '#/definitions/url.URL'
    type: object
  model.Category:
    properties:
      id:
        type: integer
      title:
        type: string
      visibility:
        type: integer
    type: object
  model.Entry:
    properties:
      author:
        type: string
      collectedOn:
        type: string
      content:
        type: string
      feedId:
        type: integer
      id:
        type: integer
      isRead:
        type: boolean
      isStarred:
        type: boolean
      link:
        $ref: '#/definitions/url.URL'
      originalId:
        type: string
      publishedOn:
        type: string
      title:
        type: string
    type: object
  model.EntryStatus:
    enum:
    - read
    - unread
    type: string
    x-enum-varnames:
    - ReadEntryStatus
    - UnreadEntryStatus
  model.Feed:
    properties:
      categoryId:
        type: integer
      feedUrl:
        $ref: '#/definitions/url.URL'
      id:
        type: integer
      isMuted:
        type: boolean
      title:
        type: string
      visibility:
        $ref: '#/definitions/model.FeedVisibility'
      websiteUrl:
        $ref: '#/definitions/url.URL'
    type: object
  model.FeedVisibility:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - ShowFeedVisibility
    - ShowInCategoryFeedVisibility
    - DoNotShowFeedVisibility
  model.SortType:
    enum:
    - ascending
    - descending
    type: string
    x-enum-varnames:
    - AscendingSort
    - DescendingSort
  model.UpdateCategoryInput:
    properties:
      title:
        type: string
      visibility:
        type: integer
    type: object
  model.UpdateEntriesInput:
    properties:
      ids:
        items:
          type: integer
        type: array
      isRead:
        type: boolean
      isStarred:
        type: boolean
    type: object
  model.UpdateEntryInput:
    properties:
      isRead:
        type: boolean
      isStarred:
        type: boolean
    type: object
  model.UpdateFeedInput:
    properties:
      categoryId:
        type: integer
      feedUrl:
        $ref: '#/definitions/url.URL'
      isMuted:
        type: boolean
      title:
        type: string
      visibility:
        $ref: '#/definitions/model.FeedVisibility'
    type: object
  url.URL:
    properties:
      forceQuery:
        description: append a query ('?') even if RawQuery is empty
        type: boolean
      fragment:
        description: fragment for references, without '#'
        type: string
      host:
        description: host or host:port (see Hostname and Port methods)
        type: string
      omitHost:
        description: do not emit empty host (authority)
        type: boolean
      opaque:
        description: encoded opaque data
        type: string
      path:
        description: path (relative paths may omit leading slash)
        type: string
      rawFragment:
        description: encoded fragment hint (see EscapedFragment method)
        type: string
      rawPath:
        description: encoded path hint (see EscapedPath method)
        type: string
      rawQuery:
        description: encoded query values, without '?'
        type: string
      scheme:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/url.Userinfo'
        description: username and password information
    type: object
  url.Userinfo:
    type: object
info:
  contact: {}
  description: RSS feed management app
  title: Gopherss API
  version: "1.0"
paths:
  /category:
    get:
      description: get categories
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: order
        type: string
      - in: query
        name: search
        type: string
      - in: query
        name: showHidden
        type: boolean
      - enum:
        - ascending
        - descending
        in: query
        name: sort
        type: string
        x-enum-varnames:
        - AscendingSort
        - DescendingSort
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Category'
            type: array
      summary: List categories
      tags:
      - category
    post:
      consumes:
      - application/json
      description: create category
      parameters:
      - description: Add category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.AddCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create category
      tags:
      - category
  /category/{id}:
    delete:
      description: delete category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Keep feeds
        in: path
        name: keepFeeds
        type: boolean
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete category
      tags:
      - category
    get:
      description: get category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get category
      tags:
      - category
    put:
      consumes:
      - application/json
      description: update category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.UpdateCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Update category
      tags:
      - category
  /entry:
    get:
      description: get entries
      parameters:
      - in: query
        name: category
        type: integer
      - in: query
        name: feed
        type: integer
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: order
        type: string
      - in: query
        name: read
        type: boolean
      - in: query
        name: search
        type: string
      - enum:
        - ascending
        - descending
        in: query
        name: sort
        type: string
        x-enum-varnames:
        - AscendingSort
        - DescendingSort
      - in: query
        name: starred
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Entry'
            type: array
      summary: List entries
      tags:
      - entry
    put:
      consumes:
      - application/json
      description: update entries
      parameters:
      - description: Update entries
        in: body
        name: entries
        required: true
        schema:
          $ref: '#/definitions/model.UpdateEntriesInput'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Update entries
      tags:
      - entry
  /entry/{id}:
    get:
      description: get entry
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Entry'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get entry
      tags:
      - entry
    put:
      consumes:
      - application/json
      description: update entry
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update entry
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/model.UpdateEntryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Entry'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Update entry
      tags:
      - entry
  /entry/{id}/mark:
    post:
      description: mark entry as read/unread
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: integer
      - enum:
        - read
        - unread
        in: query
        name: as
        type: string
        x-enum-varnames:
        - ReadEntryStatus
        - UnreadEntryStatus
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Mark as read/unread
      tags:
      - entry
  /entry/mark:
    post:
      description: mark entries as read/unread up to a timestamp
      parameters:
      - enum:
        - read
        - unread
        in: query
        name: as
        type: string
        x-enum-varnames:
        - ReadEntryStatus
        - UnreadEntryStatus
      - in: query
        name: before
        type: string
      - in: query
        name: category
        type: integer
      - in: query
        name: feed
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Mark as read/unread
      tags:
      - entry
  /feed:
    get:
      description: get feeds
      parameters:
      - in: query
        name: category
        type: integer
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: order
        type: string
      - in: query
        name: search
        type: string
      - in: query
        name: showHidden
        type: boolean
      - enum:
        - ascending
        - descending
        in: query
        name: sort
        type: string
        x-enum-varnames:
        - AscendingSort
        - DescendingSort
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Feed'
            type: array
      summary: List feeds
      tags:
      - feed
    post:
      consumes:
      - application/json
      description: create feed
      parameters:
      - description: Add feed
        in: body
        name: feed
        required: true
        schema:
          $ref: '#/definitions/model.AddFeedInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Feed'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create feed
      tags:
      - feed
  /feed/{id}:
    delete:
      description: delete feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete feed
      tags:
      - feed
    get:
      description: get feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Feed'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get feed
      tags:
      - feed
    put:
      consumes:
      - application/json
      description: update feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update feed
        in: body
        name: feed
        required: true
        schema:
          $ref: '#/definitions/model.UpdateFeedInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Feed'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Update feed
      tags:
      - feed
  /feed/{id}/icon:
    get:
      description: get feed icon
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Feed'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get feed icon
      tags:
      - feed
  /feed/{id}/refresh:
    post:
      description: refresh feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Refresh feed
      tags:
      - feed
  /feed/refresh:
    post:
      description: refresh many feeds
      parameters:
      - description: Category id
        in: query
        name: category
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Refresh feeds
      tags:
      - feed
swagger: "2.0"
